{% set name = "colcon-package-information" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/colcon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: fceeaa7b8c8ae535c52d6dacc5a3d2b7a33e6cdee4e558e300ddd12892d82192

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - colcon-core

test:
  requires:
    - python {{ python_min }}
  imports:
    - {{ name.replace("-", "_") }}

about:
  home: https://github.com/colcon/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    An extension for colcon-core to provide information about the packages.

extra:
  recipe-maintainers:
    - j-rivero
    - seanyen
    - wolfv
